name: abonmu
description: Sistem Administrasi Rumah Produksi AbonMu
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # HTTP & API
  http: ^1.2.0
  
  # State Management
  provider: ^6.1.2
  
  # Local Storage
  shared_preferences: ^2.2.3
  
  # UI Components
  cupertino_icons: ^1.0.6
  fl_chart: ^0.68.0
  intl: ^0.19.0
  
  # Icons
  flutter_svg: ^2.0.10
  
  # Image picker
  file_picker: ^8.1.7
  
  # URL launcher (untuk download PDF)
  url_launcher: ^6.3.1
  
  # PDF generation di device
  pdf: ^3.11.1
  printing: ^5.13.2
  path_provider: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo-abonmu.png
